export const GET_ERRORS = "GET_ERRORS";
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";
export const USER_EDIT = "USER_EDIT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_PENDING_SELLERS = "GET_PENDING_SELLERS"
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_APPROVED = "UPDATE_APPROVED";

export const INCREMENT = "INCREMENT";