export const GET_ERRORS = "GET_ERRORS";
// Admin users
export const USER_EDIT = "USER_EDIT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_UNAPPROVED_USERS = "GET_UNAPPROVED_USERS"
export const USER_LOADING = "USER_LOADING";
export const USER_EDIT_LOADING = "USER_EDIT_LOADING";
// Login
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const SET_CURRENT_USER_DETAILS = "SET_CURRENT_USER_DETAILS";
export const GET_CURRENT_USER_DETAILS = "GET_CURRENT_USER_DETAILS";
export const INCREMENT = "INCREMENT";

// Book
export const UPDATE_BOOK = "UPDATE_BOOK";
export const GET_BOOK_LIST = "GET_BOOK_LIST";
export const GET_PENDING_BOOK_LIST = "GET_PENDING_BOOK_LIST";
export const GET_SEARCHED_BOOKS = "GET_SEARCHED_BOOKS";
export const BOOK_LOADING = "BOOK_LOADING";
export const BOOK_EDIT_LOADING = "BOOK_EDIT_LOADING";
export const GET_CATEGORY = "GET_CATEGORY";

// Transactions
export const CREATE_TRANSACTION = "CREATE_TRANSACTION"; 
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const GET_SELLER_TRANSACTIONS = "GET_SELLER_TRANSACTIONS";
export const GET_USER_BOOKS = "GET_USER_BOOKS"

// Cart
export const UPDATE_CART = "UPDATE_CART"
export const GET_CART = "GET_CART";

// Review
export const UPDATE_REVIEW = "UPDATE_REVIEW"
export const GET_REVIEW = "GET_REVIEW";
export const  GET_ALL_REVIEWS = "GET_ALL_REVIEWS";