# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  backendbuild:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Login microservice
          command: |
            cd ~/project/BackEnd/loginmicroservices
            .\mvnw package
      - run:
          name: book microservice
          command: |
            cd ~/project/BackEnd/bookmicroservices
            .\mvnw package
      - run:
          name: transactions microservice
          command: |
            cd ~/project/BackEnd/transactionsmicroservices
            .\mvnw package
      - persist_to_workspace:
          root: ~/project/BackEnd/
          paths:
            - loginmicroservices\target\loginmicroservices-0.0.1.jar
            - transactionsmicroservices\target\transactionsmicroservices-0.0.1.jar
            - bookmicroservices\target\bookmicroservices-0.0.1.jar
  frontendbuild:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd ~/project/FrontEnd/myfirstapp
            npm install

  tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/BackEnd
      - run:
          name: Install Dependencies
          background: yes
          command: |
            java -jar ~/project/BackEnd/loginmicroservices\target\loginmicroservices-0.0.1.jar
            
workflows:
  build:
    jobs:
      - backendbuild
      - frontendbuild
      - tests

