# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd ~/project/FrontEnd/myfirstapp
            npm install
      - run:
          name: Run tests
          command: 
            cd ~/project/FrontEnd/myfirstapp|
            npm run test
workflows:
  build:
    jobs:
      - install
