# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  backendbuild:
    docker:
      - image: cimg/openjdk:16.0.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            mvn -N io.takari:maven:wrapper
      - run:
          name: Login microservice
          command: |
            cd ~/project/BackEnd/loginmicroservices
            chmod u+x ~/project/BackEnd/loginmicroservices/mvnw
            ~/project/BackEnd/loginmicroservices/mvnw package
      - run:
          name: book microservice
          command: |
            cd ~/project/BackEnd/booksmicroservices
            chmod u+x ~/project/BackEnd/booksmicroservices/mvnw
            ~/project/BackEnd/booksmicroservices/mvnw package
      - run:
          name: transactions microservice
          command: |
            cd ~/project/BackEnd/transactionsmicroservices
            chmod u+x ~/project/BackEnd/transactionsmicroservices/mvnw
            ~/project/BackEnd/transactionsmicroservices/mvnw package
      - persist_to_workspace:
          root: ~/project/BackEnd/
          paths:
            - ~/project/BackEnd/loginmicroservices/target/loginmicroservices-0.0.1.jar
            - ~/project/BackEnd/transactionsmicroservices/target/transactionsmicroservices-0.0.1.jar
            - ~/project/BackEnd/booksmicroservices/target/booksmicroservices-0.0.1.jar
  frontendbuild:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cd ~/project/FrontEnd/myfirstapp
            npm install

  tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/BackEnd
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install default-jdk
      - run:
          name: Run service
          background: yes
          command: |
            java -jar ~/project/BackEnd/loginmicroservices\target\loginmicroservices-0.0.1.jar
            
workflows:
  build:
    jobs:
      - backendbuild
      - frontendbuild:
          requires:
            - backendbuild
      - tests:
          requires:
            - frontendbuild
            - backendbuild

